### ISSUE TITLE
peerDependencies

### ISSUE THREAD

**Issue by patrickjtoy** [mrkev/generator-typescript#3]
`$ npm install -g generator-typescript`

`npm WARN peerDependencies The peer dependency yo@>=1.3.3 included from generator-typescript will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.`

**Comment by mrkev** [comment]
Hmm noted. I'm not sure depending on `yo` explicitly is what we want, probably removing the dependency altogether will be the course of action to take. Will leave open until npm 3 comes around and I see what other generators are doing.

**Comment by BjornMelgaard** [comment]
npm 3 had come already, and this error persist :smile:

**Comment by mrkev** [comment]
Ah, true 😅
Fixed 👍

**Comment by BjornMelgaard** [comment]
thanks, @mrkev, very useful generator
