### ISSUE TITLE
Improvement: add typings

### ISSUE THREAD

**Issue by BjornMelgaard** [mrkev/generator-typescript#5]
It will be more convenient to have [gulp-typings](https://www.npmjs.com/package/gulp-typings) preinstalled

**Comment by mrkev** [comment]
nice, will add as soon as I get a chance

**Comment by mrkev** [comment]
Noticed typescript 2.0 [just came out](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/), and type declarations are now handled by npm. The release blog-post includes this:

> It’s worth noting that both Typings and tsd will continue to work for existing projects, however 2.0-compatible declaration files may not be available through these tools. As such, we strongly recommend upgrading to the new npm workflow for TypeScript 2.0 and beyond.

I think it'd be best to hold on including gulp-typings here, now that the preferred method seems to be npm.

**Comment by BjornMelgaard** [comment]
Nice, predict occurrence of new novel errors :smile:
