### ISSUE TITLE
Usage with gulp-concat

### ISSUE THREAD

**Issue by alesmit** [mrkev/generator-typescript#6]
I want my project to be in a single js file, so I installed the plugin `gulp-concat` and added the pipe in the gulpfile.js.
My main.ts requires classes from other .ts files in the src directory. When I build, the compiled code goes in a single .js as it should be, but when I try to run it, I got a "module not found" error.
In fact, the compiled .js still has the `require` statements.
What am I missing?

**Comment by mrkev** [comment]
This is a question for `gulp-concat` or stackoverflow.
